version: "2"

services:
  rng:
    build: rng
    ports:
    - "8001:8000"

  hasher:
    build: hasher
    ports:
    - "8002:8000"

  webui:
    build: webui
    ports:
    - "8000:8000"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis

  worker:
    build: worker

