apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webui
spec:
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: rng
        image: image-registry.openshift-image-registry.svc:5000/dockercoins/webui:latest
        ports:
        - containerPort: 8000
