apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: image-registry.openshift-image-registry.svc:5000/dockercoins/hasher:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  selector:
    app: hasher
  ports:
  - port: 80
    targetPort: 8000
