apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: image-registry.openshift-image-registry.svc:5000/dockercoins/rng:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  selector:
    app: rng
  ports:
  - port: 80
    targetPort: 8000
