kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dockercoins-role-binding
  namespace: dockercoins
subjects:
- kind: ServiceAccount
  name: dockercoins
  apiGroups: ["", "extensions", "apps"]
  namespace: dockercoins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin