kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: dockercoins
  name: dockercoins
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments, services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]