kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: dockercoins-role-binding
subjects: 
- kind: ServiceAccount 
  name: dockercoins
  apiGroup: ""
roleRef: 
  kind: Role
  name: dockercoins
  apiGroup: ""